name: 'call-multi-approvers'

on:
  pull_request:
    types:
      - 'opened'
      - 'edited'
      - 'reopened'
      - 'synchronize'
      - 'ready_for_review'
      - 'review_requested'
      - 'review_request_removed'
  pull_request_review:
    types:
      - 'submitted'
      - 'dismissed'

permissions:
  actions: 'write'
  contents: 'read'
  pull-requests: 'read'

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  checkout-javascript:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout multi-approver.js'
        uses: 'actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b' # ratchet:actions/checkout@v4
        with:
          path: 'abcxyz/pkg'
          repository: 'ian-shafer/playground'
          sparse-checkout: |
            .github/workflows/multi-approvers.js
          sparse-checkout-cone-mode: false

  check-checkout:
    run: |
      ls abcxyz/pkg/.github/workflows

  multi-approvers:
    needs: 'checkout-javascript'
    uses: 'ian-shafer/playground/.github/workflows/multi-approvers.yml@main'
    with:
      org-members-path: './members.json'
